Repository googleapis/python-api-gateway, pull requests merged in 2021-04, with the labels that each got.

#3 fix: use correct retry deadline
  .pre-commit-config.yaml
  docs/conf.py
  google/cloud/apigateway_v1/services/api_gateway_service/async_client.py
  google/cloud/apigateway_v1/services/api_gateway_service/transports/base.py
  google/cloud/apigateway_v1/services/api_gateway_service/transports/grpc.py
  google/cloud/apigateway_v1/services/api_gateway_service/transports/grpc_asyncio.py
  noxfile.py
  setup.py
  synth.metadata
  synth.py
  testing/constraints-3.6.txt
Labels: api: apigateway, cla: yes, context: partial

#6 chore: start tracking obsolete files
  synth.metadata
Labels: api: apigateway, cla: yes, context: full

#7 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: apigateway, cla: yes, context: full

#8 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: apigateway, cla: yes, context: full, samples

#11 chore: prevent normalization of semver versioning
  setup.py
Labels: api: apigateway, cla: yes

#10 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#12 chore(revert): revert preventing normalization
  setup.py
Labels: api: apigateway, cla: yes
